### PR TITLE
Adding new kind of action which is performed in response to the error.

### PR DESCRIPTION
**Pull request by NeoAnomaly**
Related to #17

### CODE REVIEW

**Comment by bchavez** [comment]
Hi @NeoAnomaly , thanks very much for your PR. This looks like a reasonable addition.

I wanted to reach out to you and ask if you could also make the .NET/managed version include the changes your PR.

I checked the CI build output for this PR and (`BugTrapDN.dll`) and found `enum ActivityType` still having `MailReport`, `SaveReport`, `SendReport`, and `ShowUI`. I don't see a new `Custom` value with an ability to register a callback in the .NET version of BugTrap.

If you could make the .NET version match up with the changes you made in the native version of BugTrap, that would be really great!

Let me know your thoughts. Thanks!

**Comment by NeoAnomaly** [comment]
Hi @bchavez. I tried to made suitable changes for managed version. At first glance nothing complicated. But it would be better if someone who knows/works with c++/cli reviewed changes before merging.

Example usage(C#):
```
class Program
    {
        static void Main(string[] args)
        {
            ExceptionHandler.AppName = "Your application name";
            ExceptionHandler.Flags = FlagsType.DetailedMode;
            ExceptionHandler.DumpType = MinidumpType.Normal;

            ExceptionHandler.Activity = ActivityType.Custom;
            ExceptionHandler.CustomActivity += ExceptionHandler_CustomActivity;

            throw new NotImplementedException("My test exception");
        }

        private static void ExceptionHandler_CustomActivity(object sender, string reportFilePath)
        {
            Console.WriteLine(reportFilePath);
            Console.ReadLine();
        }
    }
```

**Comment by bchavez** [comment]
Hi @NeoAnomaly , this looks great! Thanks so much for getting the managed version up to feature parity with your PR.

It looks good to me. I'll probably wait until the end of day before merging your code to give others a chance to review this PR.

If we don't have any objections, we'll merge tonight (Los Angeles/Pacific Time) and publish a fresh build of your changes.

Again, thank you for your contribution! Great work m8!

**Comment by gvanem** [comment]
> Related to #17

Good!

**Pull request merged**
