### PR TITLE
Add missing sources/projects/solutions

### PR DESCRIPTION
**Pull request by nitrocaster**
Originally BugTrap comes with the CrashExplorer, windows standalone server, windows web server, java server and a bunch of example projects - now they're all included.

### CODE REVIEW

**Comment by nitrocaster** [comment]
Regarding AppVeyor build failure: WTL is required by CrashExplorer and is included as NuGet package, but msbuild doesn't download it automatically.

**Comment by bchavez** [comment]
Awesome work! Great. Thanks very much. I checked-out your PR seperately and restored nuget packages, are we also going to need boost? 

After restoring WTL from nuget we have:
```
c:\temp\bt2\bugtrap\source\crashexplorer\stdafx.h(73): fatal error C1083: Cannot open include file: 'boost/regex.hpp': No such file or directory [C:\temp\bt2\BugTrap\source\CrashExplorer\CrashExplorer.vs2013.vcxproj]
Done Building Project "C:\temp\bt2\BugTrap\source\CrashExplorer\CrashExplorer.vs2013.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\temp\bt2\BugTrap\source\BugTrap.vs2013.sln" (default targets) -- FAILED.


Build FAILED.

"C:\temp\bt2\BugTrap\source\BugTrap.vs2013.sln" (default target) (1) ->
"C:\temp\bt2\BugTrap\source\CrashExplorer\CrashExplorer.vs2013.vcxproj" (default target) (5) ->
(ClCompile target) ->
  c:\temp\bt2\bugtrap\source\crashexplorer\stdafx.h(73): fatal error C1083: Cannot open include file: 'boost/regex.hpp': No such file or directory [C:\temp\bt2\BugTrap\source\CrashExplorer\CrashExplorer.vs2013.vcxproj]
```

**Comment by nitrocaster** [comment]
And we need boost too. Is there a way to fix that without adding boost source to the repository?

**Comment by bchavez** [comment]
@nitrocaster you can also modify build.cmd before build:
```
nuget restore source\BugTrap.vs2013.sln
```
AppVeyor has a slew of frameworks and software installed (including nuget commandline) and boost:
http://www.appveyor.com/docs/installed-software

Boost:
* 1.59.0 (C:\Libraries\boost_1_59_0)
* 1.58.0 (C:\Libraries\boost_1_58_0)
* 1.56.0 (C:\Libraries\boost

**Comment by nitrocaster** [comment]
Another thing.
Demo projects require multibyte MFC library that has been broken out of the VS2013 and later versions (error MSB8031).
The library has to be downloaded and installed separately: [Multibyte MFC Library for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40770)

**Comment by bchavez** [comment]
We still might be able to pull off the Multibyte MFC dependency using a pre-install script:

http://help.appveyor.com/discussions/questions/1464-multibyte-mfc-library-for-visualstudio-2013

**Comment by nitrocaster** [comment]
> nuget restore source\BugTrap.vs2013.sln

Seems that should work without such command:

> If you have enabled NuGet Package Restore for Visual Studio solution it will be automatically triggered in the AppVeyor build environment as EnableNuGetPackageRestore environment variable is already set to true.

**Comment by bchavez** [comment]
@nitrocaster I think it is ture if we used AppVeyor's automatic `build:` task, but we are using our custom `build_script: build.cmd`. Perhaps automatic package restore is not enabled if manual `build_script:` is used.

**Comment by nitrocaster** [comment]
Deal with WTL, now it fails because of the boost.

**Comment by bchavez** [comment]
Awesome. Thanks @nitrocaster , should we merge now ? or do you want to try to enable boost from appveyor's library folder?

Boost
* 1.59.0 (C:\Libraries\boost_1_59_0)
* 1.58.0 (C:\Libraries\boost_1_58_0)
* 1.56.0 (C:\Libraries\boost

**Comment by nitrocaster** [comment]
Will try to get it passing AppVeyor.

**Comment by nitrocaster** [comment]
Looks like AppVeyor doesn't have precompiled boost libraries.

**Comment by nitrocaster** [comment]
Something weird is going on here: with `-p:useenv=true` msbuild runs 32-bit CL which produces objects with target machine flag X86. Without that - it runs 64-bit CL, as it should, and build succeeds.

**Comment by bchavez** [comment]
Perhaps an easier approach would be a boost nuget package?

https://www.nuget.org/packages/boost/

**Comment by bchavez** [comment]
Also, seems like after reviewing a few example appveyor.yaml files from other github projects, it appears everyone tends to use `cmake` to build boost in `c:\libraries\boost`

**Comment by bchavez** [comment]
https://github.com/jfalcou/nstest/blob/master/appveyor.yml

```
environment:
  BOOST_ROOT: c:\Libraries\boost
  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib

# scripts to run before build
before_build:
...
  - cmake -G"Visual Studio 12 2013 Win64" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..

**Comment by nitrocaster** [comment]
It's ok now, you can merge.

**Comment by bchavez** [comment]
Awesome work @nitrocaster ! :+1:

**Pull request merged**
