### PR TITLE
fixed link to Developer Guide PDF in Readme

### PR DESCRIPTION
**Pull request by abdul-sami**

### CODE REVIEW

**Comment by nitrocaster** [comment]
Wow, for some reason boost fails to build.

**Comment by abdul-sami** [comment]
This looks like a problem with Appveyor if it was building previously. My change is quite innocent :smile:

**Comment by bchavez** [comment]
Hi there,

Thank you for the PR.

Yea, the VM image on **AppVeyor** changed recently. So, some `boost` build paths are a bit out of sync. I'll fix these later tonight.

**Comment by bchavez** [comment]
Build system should be fixed on future PRs now. Thanks!

**Pull request merged**
