### PR TITLE
Add support for VS2019 & VS2022

### PR DESCRIPTION
**Pull request by Brouilles**
Add Visual Studio projects for 2019 and 2022.

### CODE REVIEW

**Comment by Brouilles** [comment]
If you have any problem with the PR. Don't hesitate. 👍

**Comment by bchavez** [comment]
Hey there, sorry for the delay, havent had a chance to check this yet; was working hard on another OSS repo this weekend 🥵 ; but I ran out of time this week. I'll try to get to this coming week/weekend.

Also, quick tip for the future: If possible, it would help to keep PRs small so they can be easily reviewed. Large PRs with 5000+ line changes take more time to review.

**Comment by Brouilles** [comment]
Hi!
Can expect some news about this PR? 100% of the files are Visual Studio project configuration, not "real code". Can be good to the PR merged soon!

**Comment by Brouilles** [comment]
A up for the PR.

**Comment by Brouilles** [comment]
New up for the PR.

**Pull request closed without merging**
