### PR TITLE
display version number in about dialog and changed last untranslated button

### PR DESCRIPTION
**Pull request by sesom42**
This commit displays the version number pulled from loaded module (dll) into the about dialog.

I have not changed the display of the license because I'm not sure how to handle this correctly. Suggestions?

### CODE REVIEW

**Comment by bchavez** [comment]
Hi @sesom42 , thanks for your contributions so far. I've contacted the author, hopefully we'll be able to provide some additional clarification. I'll wait for his comments before merging.

**Comment by bchavez** [comment]
Hi @sesom42 , I've been in contact with the original author and he has granted us permission to change the license in this repository to a more permissible MIT license.

He will also change his CodeProject article to point to this repo along with the MIT licence change later this evening (Los Angeles / Pacific Time).

In regard to the "about" dialog, could you post a quick screenshot in regards to your specific question? The MIT licence has been changed in latest commit to the repository.

**Comment by sesom42** [comment]
I have not changed anything about the licence in "about" dialog. But I will wait until the author hast posted the licence change on CodeProject and then I will submit another pull request. Is it ok to cancel this pull request for now? After licence change I'll adapt the "about" dialog and post a screenshot along with the pull request, ok?

**Comment by bchavez** [comment]
Sure thing m8. Merged.

**Comment by bchavez** [comment]
@sesom42 
The License and Links have been updated on the code project article. http://www.codeproject.com/Articles/14618/Catch-All-Bugs-with-BugTrap

**Comment by bchavez** [comment]
Also, I have the latest snapshot the author sent. I'll be adding the BugTrap server-side code soon.

**Pull request merged**
